// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BDORkn97RB2-Xm1df9_OcPC1pDjE8qg',
    appId: '1:467565232511:web:0a0cbda719dea1a49d1a4a',
    messagingSenderId: '467565232511',
    projectId: 'chat-app-2-80c17',
    authDomain: 'chat-app-2-80c17.firebaseapp.com',
    storageBucket: 'chat-app-2-80c17.firebasestorage.app',
    measurementId: 'G-GGP61WPZKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNQ6oe5VoT_us7NxapiGmxWyRrUjg_BmE',
    appId: '1:467565232511:android:7309104657d679a99d1a4a',
    messagingSenderId: '467565232511',
    projectId: 'chat-app-2-80c17',
    storageBucket: 'chat-app-2-80c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPUPQS0gidZP6Rld3-yJaurCwZTMNw7S4',
    appId: '1:467565232511:ios:421fbb2cc5d42b089d1a4a',
    messagingSenderId: '467565232511',
    projectId: 'chat-app-2-80c17',
    storageBucket: 'chat-app-2-80c17.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPUPQS0gidZP6Rld3-yJaurCwZTMNw7S4',
    appId: '1:467565232511:ios:421fbb2cc5d42b089d1a4a',
    messagingSenderId: '467565232511',
    projectId: 'chat-app-2-80c17',
    storageBucket: 'chat-app-2-80c17.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7BDORkn97RB2-Xm1df9_OcPC1pDjE8qg',
    appId: '1:467565232511:web:862a347321e71e019d1a4a',
    messagingSenderId: '467565232511',
    projectId: 'chat-app-2-80c17',
    authDomain: 'chat-app-2-80c17.firebaseapp.com',
    storageBucket: 'chat-app-2-80c17.firebasestorage.app',
    measurementId: 'G-25R9PC13D8',
  );
}
